version: '3.8'
services:
  db_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: djs9usaf
      MYSQL_USER: muser
      MYSQL_PASSWORD: da89hY7UH
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
volumes:
  db_data: