version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: asfdfdabhg
      MYSQL_DATABASE: back-ubicatp
      MYSQL_USER: cico
      MYSQL_PASSWORD: dsafarfsa
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/back-ubicatp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: asfdfdabhg
    volumes:
      - .:/app
    command: ["mvn", "spring-boot:run"]

volumes:
  mysql-data:
